version: '3.7'
services:
  mongo:
    image: mongo:3.4
    restart: always
    volumes:
      - ./database:/data/db:rw
    ports:
      - "27017:27017/tcp"

  controller:
    build: 
      context: .
    depends_on:
      - mongo
    init: true
    extra_hosts:
        - "mongo:127.0.0.1"
    network_mode: host
    volumes:
      - ./unifi:/unifi:rw
      - ./system.properties:/unifi/system.properties
    ports: 
      - "3478:3478/udp" # STUN
      - "6789:6789/tcp" # Speed test
      - "8080:8080/tcp" # Device/ controller comm.
      - "8443:8443/tcp" # Controller GUI/API as seen in a web browser
      - "8880:8880/tcp" # HTTP portal redirection
      - "8843:8843/tcp" # HTTPS portal redirection
      - "10001:10001/udp" # AP discovery
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 5m
